# TODO: adapt to scala
# This is a basic workflow to help you get started with Actions
#
#name: CI
#
## Controls when the action will run.
#on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.13
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.13
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build with Maven
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: mvn --batch-mode --update-snapshots -U verify